version: '3'

services:
  nodejs:
    container_name: warga-post-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:2525"
    restart: unless-stopped
    networks:
      - gateway    


networks:
  gateway:
    name: npm_gateway
    external: true