version: '3'

services:
  nodejs:
    container_name: warga-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - gateway    

networks:
  gateway:
    name: gateway
    external: true