name: Build & Deploy
on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
     - name: Deploy nodejs function
       uses: appleboy/ssh-action@v0.1.2
       with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}

        script: |
          cd ~/warga/backend/api
          git pull
          docker compose up --build -d
          echo "apii built"

          cd ~/warga/frontend
          docker compose up --build -d
          echo "frontend built"
